include(${CODE_DIR}/source_groups.cmake)

set(PQC_FUSE_SOURCES
    ${PQC_FUSE_FRONTEND_CORE_SOURCES}
    ${PQC_FUSE_CRYPTO_SOURCES}
    ${PQC_FUSE_STORAGE_SOURCES}
    ${PQC_FUSE_RUNTIME_SOURCES}
    ${PQC_FUSE_FILESYSTEM_SOURCES}
    ${PQC_FUSE_SUPPORT_SOURCES}
)

set(PQC_FUSE_ENTRY_SOURCES
    ${PQC_FUSE_FRONTEND_ENTRY_SOURCES}
)
