if(CMAKE_CUDA_COMPILER)
    message(STATUS " CUDA AEAD target        : skim_cuda_aead enabled")
    if(HAS_CUPQC)
        message(STATUS " CUDA ML-KEM target      : skim_cuda_pqc enabled")
        message(STATUS " CUDA ML-KEM benchmark   : bench_gpu_pqc enabled")
    else()
        message(STATUS " CUDA ML-KEM target      : disabled; cuPQC not found")
        message(STATUS " CUDA ML-KEM benchmark   : disabled; cuPQC not found")
    endif()
    if(CUPQC_HASH_LIB)
        message(STATUS " CUDA integrity source   : cuda_integrity.cu attached")
        message(STATUS " CUDA integrity benchmark: bench_gpu_integrity enabled")
    else()
        message(STATUS " CUDA integrity source   : disabled; cuPQC-HASH not found")
        message(STATUS " CUDA integrity benchmark: disabled; cuPQC-HASH not found")
    endif()
else()
    message(STATUS " CUDA backend targets    : disabled; CUDA compiler not found")
endif()
